### ISSUE TITLE
dmic internal

### ISSUE THREAD

**Issue by Lorys89** [Speeedo83/Dell-Inspiron-5491-2-1-Hackintosh#1]
hi you have a problem with internal microphone? if yes, you buy a mini dongle mic! 😇❤️

**Comment by Speeedo83** [comment]
Yes,  the internal microphone and the headphone microphone of the combo jack do not work, instead internal audio work fine

**Comment by Speeedo83** [comment]
I buy it... But I want't have a shortcut, you can help me?

**Comment by Lorys89** [comment]
> Lo compro ... Ma non voglio avere una scorciatoia, mi puoi aiutare?

yes, sell your pc and buy a real mbp 😂

**Comment by Speeedo83** [comment]
Just fine, send me a 1500 euro

**Comment by Lorys89** [comment]
💶x1500 📨

**Comment by Speeedo83** [comment]
tnk

**Comment by Lorys89** [comment]
привет мой друг 😘
